config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get "/orders/:id/confirmed", to: "orders#show_confirmed", as: "order_confirmed"
  authenticate :user do
    resources :users, only: [:show, :edit, :update]
    resources :modes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'search_vehicles', on: :collection, as: 'search_vehicles'
    end
    resources :prices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'search_orders', on: :collection, as: 'search_all'
      resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :budgets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end

  resources :orders, only: [:show, :show_confirmed] do
    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :show]
    resources :order_products, only: [:index, :show]
    resources :order_addresses, only: [:index, :show]
    resources :budgets, only: [:index, :show]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    post 'returned', on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :orders, through: :order_addresses

  validates :person, :address_one, :city, :state, :zip, presence: true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :order
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  belongs_to :mode
  validates :min_distance, :max_distance, :deadline, :mode_id, presence: true
end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :vehicles
  has_many :prices
  has_many :deadlines
  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :addresses, through: :order_addresses
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  has_one :budgets, dependent: :destroy

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :order_products, allow_destroy: true

  enum status: { open:0, pending: 3, sent: 5, delivered: 10, canceled: 15, returned: 20 }

  enum condition: { on_time: 0, late: 10 }

  enum state: [ :AC, :AL, :AP, :AM, :BA, :CE, :DF, :ES, :GO, :MA, :MT, :MS, :MG, :PA, :PB, :PR, :PE, :PI, :RJ, :RN, :RS, :RO, :RR, :SC, :SP, :SE, :TO ]

  validates :distance, :status, presence: true
  validates_associated :order_products

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def addresses_attributes=(addresses_attributes)
    addresses_attributes.values.each do |address_attributes|
      self.addresses.build(address_attributes)
    end
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :order
  belongs_to :address

  # accepts_nested_attributes_for :address, allow_destroy: true
  validates_associated :address
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  accepts_nested_attributes_for :product, allow_destroy: true
  validates_associated :product, presence: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :mode
  validates :min_weight, :max_weight, :price_per_km, :mode_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products

  validates :code, :width, :height, :depth, :weight, presence: true

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :mode

  validates :mode_id, :plate, :brand, :model, :category, :year, :capacity, :status, presence: true

  enum status: { operational: 0, transit: 5, repair: 10 }
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/shared/_user_header.html.erb
<div class="fixed-top d-flex flex-column flex-shrink-0 p-3 text-bg-dark header__vertical" style="width: 280px;">
  <p>
    <%= link_to root_path, 
      class: 'd-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none logo' do %>
      <i class="fa fa-truck-fast"></i>&nbsp;&nbsp;<%= t('fastlog') %>
    <% end %>
  </p>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to root_path, class: "nav-link text-white #{ current_page?(root_path) ? 'active' : ''}" do %>
        <i class="fa fa-house"></i>&nbsp;&nbsp;<%= t('dashboard') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to orders_path, class: "nav-link text-white #{ current_page?(controller: 'orders') ? 'active' : ''}" do %>
        <i class="fa-solid fa-cube"></i>&nbsp;&nbsp;<%= t('orders') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to modes_path, class: "nav-link text-white #{ current_page?(controller: 'modes') ? 'active' : ''}" do %>
        <i class="fa fa-globe"></i>&nbsp;&nbsp;<%= t('modes') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to vehicles_path, class: "nav-link text-white #{ current_page?(controller: 'vehicles') ? 'active' : ''}" do %>
        <i class="fa fa-truck"></i>&nbsp;&nbsp;<%= t('vehicles') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to prices_path, class: "nav-link text-white #{ current_page?(controller: 'prices') ? 'active' : ''}" do %>
        <i class="fa-solid fa-dollar"></i>&nbsp;&nbsp;<%= t('prices') %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to deadlines_path, class: "nav-link text-white #{ current_page?(controller: 'deadlines') ? 'active' : ''}" do %>
        <i class="fa-solid fa-hourglass-half"></i>&nbsp;&nbsp;<%= t('deadlines') %>
      <% end %>
    </li>
  </ul>
  <hr>
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="/images/user.png" alt="" width="32" height="32" class="rounded-circle me-2">
      <strong><%= current_user.name %> </strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
      <li><%= link_to t("profile"), user_path(current_user.id), class: "dropdown-item" %></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to t("sign_out"), destroy_user_session_path, method: :delete, class: 'dropdown-item header__vertical-logout' %></li>
    </ul>
  </div>
</div>

app/views/shared/_visitor_header.html.erb
<div class="<%= 'header__horizontal bg-dark' if (!@home && !request.path.match(/^\/users\/[^\d]+$/).present?) %>">
  <nav class="navbar flex-column container">
    <div class="container-fluid">
      <div>
        <h2><i class='fa fa-truck-fast'></i>&nbsp;&nbsp;<%= link_to t('fastlog'), root_path, class: "navbar-brand logo2" %></h2>
      </div>
      <div class="">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to t('log_in'), new_user_session_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</div>