config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get "/orders/:id/confirmed", to: "orders#show_confirmed", as: "order_confirmed"
  authenticate :user do
    resources :users, only: [:show, :edit, :update]
    resources :modes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'search_vehicles', on: :collection, as: 'search_vehicles'
    end
    resources :prices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'search_orders', on: :collection, as: 'search_all'
      resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :budgets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end

  resources :orders, only: [:show, :show_confirmed] do
    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :show]
    resources :order_products, only: [:index, :show]
    resources :order_addresses, only: [:index, :show]
    resources :budgets, only: [:index, :show]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    post 'returned', on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :orders, through: :order_addresses

  validates :person, :address_one, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :order
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  belongs_to :mode
  validates :min_distance, :max_distance, :deadline, :mode_id, presence: true
end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :vehicles
  has_many :prices
  has_many :deadlines
  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :addresses, through: :order_addresses
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  has_one :budgets, dependent: :destroy

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :order_products, allow_destroy: true

  enum status: { open:0, pending: 3, sent: 5, delivered: 10, canceled: 15, returned: 20 }

  enum condition: { on_time: 0, late: 10 }

  enum state: [ :AC, :AL, :AP, :AM, :BA, :CE, :DF, :ES, :GO, :MA, :MT, :MS, :MG, :PA, :PB, :PR, :PE, :PI, :RJ, :RN, :RS, :RO, :RR, :SC, :SP, :SE, :TO ]

  validates :distance, :status, presence: true
  validates_associated :order_products

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def addresses_attributes=(addresses_attributes)
    addresses_attributes.values.each do |address_attributes|
      self.addresses.build(address_attributes)
    end
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :order
  belongs_to :address

  # accepts_nested_attributes_for :address, allow_destroy: true
  validates_associated :address
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  accepts_nested_attributes_for :product, allow_destroy: true
  validates_associated :product, presence: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :mode
  validates :min_weight, :max_weight, :price_per_km, :mode_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products

  validates :code, :width, :height, :depth, :weight, presence: true

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :mode

  validates :mode_id, :plate, :brand, :model, :category, :year, :capacity, :status, presence: true

  enum status: { operational: 0, transit: 5, repair: 10 }
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :mode_find, only: [:show, :edit, :update, :destroy] 

  def index
    @modes = Mode.all
  end

  def show
    @prices = Price.where(mode_id: @mode.id).order(:min_weight)
    @deadlines = Deadline.where(mode_id: @mode.id).order(:min_distance)
    @in_operation = Vehicle.where(mode_id: @mode.id).where(:status => [:in_operation, :in_transit]).order(:plate)  
    @in_maintenance = Vehicle.where(mode_id: @mode.id, status: :in_maintenance).order(:plate)
  end

  def destroy
    if @mode.destroy
      flash[:notice] = "Modalidade apagada com sucesso"
      return redirect_to modes_path
    end
    flash.now[:alert] = "Erro ao apagar a modalidade"
    render :show, status: :unprocessable_entity
  end

  def new
    @mode = Mode.new
  end

  def create
    @mode = Mode.new(mode_params)
    if @mode.save
      flash[:notice] = t("mode_created_sucessfully")
      return redirect_to modes_path
    end
    flash.now[:alert] = t("error_on_creating_mode")
    render :new, status: :unprocessable_entity
  end

  def edit
  end

  def update
    if @mode.update(mode_params)
      flash[:notice] = "Modalidade atualizada com sucesso"
      return redirect_to @mode
    end
    flash.now[:alert] = "Erro ao atualizar a modalidade"
    render :edit, status: :unprocessable_entity
  end

  private

  def mode_params
    params.require(:mode).permit(:name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, :active)
  end

  def mode_find
    @mode = Mode.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/modes/_form.html.erb
<!-- Existe alguma mensagem de erro de sistema? -->
<% if(mode.errors.any?) %>
  <div class="messages alert alert-warning" role="alert">
    <p><%= t('verify_the_following_errors') %>:</p>
    <ul>
      <% mode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form">
  <%= form_with(model: mode) do |f| %>
    <table class="modes__form table table-success table-striped">
      <tr>
        <th><%= f.label :name, class: "form-label" %></th>
        <td><%= f.text_field :name, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :min_distance, t('min_distance') << ' (Km)', class: "form-label" %></th>
        <td><%= f.number_field :min_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_distance, t('max_distance') << ' (Km)', class: "form-label" %></th>
        <td><%= f.number_field :max_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :min_weight, t('min_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :min_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_weight, t('max_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :max_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :fixed_fee, t('fixed_fee') << ' (R$)', class: "form-label" %></th>
        <td><%= f.number_field :fixed_fee, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :active, t('status'), class: "form-label" %></th>
        <td>
          <%= f.check_box :active, class: "form-check-input" %> 
        </td>
      </tr>
    </table>
    <div class="modes__btn">
      <%= f.submit t('save'), class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/modes/edit.html.erb
<section>
  <div class="modes">
    <h1><%= t('edit') << " " << t('mode') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), modes_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    <%= render partial: "form", locals: { mode: @mode } %>
  </div>
</section>

app/views/modes/index.html.erb
<section>
  <div class="modes">
    <h1><%= t('modes') %></h1>
    <div class="page__top">
      <%= button_to(t("new_mode"), new_mode_path, method: :get, class: "btn btn-primary") %>
    </div>
  </div>
  <div class="modes__list">
    <% if @modes.empty? %>
      <h3><%= t('no_modes_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('name') %></th>
            <th scope="col"><%= t('min_distance') %> (Km)</th>
            <th scope="col"><%= t('max_distance') %> (Km)</th>
            <th scope="col"><%= t('min_weight') %> (Kg)</th>
            <th scope="col"><%= t('max_weight') %> (Kg)</th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @modes.each do |mode| %>
            <tr>
              <td scope="row"><%= link_to mode.name, mode_path(mode.id) %></td>
              <td><%= mode.min_distance %></td>
              <td><%= mode.max_distance %></td>
              <td><%= mode.min_weight %></td>
              <td><%= mode.max_weight %></td>
              <td>
                <span class="<%= mode.active ? 'ativo' : 'inativo' %>">
                  <%= mode.active ? t('active') : t('inactive') %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/modes/new.html.erb
<section>
  <div class="modes">
    <h1><%= t('new_mode') %> </h1>
    <div class="page__top">
      <%= button_to(t("back"), modes_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
  </div>
  <div class="modes__list">
    <%= render partial: "form", locals: { mode: @mode } %>
  </div>
</section>

app/views/modes/show.html.erb
<section>
  <div class="modes">
    <h1><%= t('mode') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), modes_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    
    <table class="modes__table table table-success table-striped">
      <tr>
        <th><%= t('name') %></th>
        <td><%= @mode.name %></td>
      </tr>
      <tr>
        <th><%= t('min_distance') %></th>
        <td><%= @mode.min_distance %> Km</td>
      </tr>
      <tr>
        <th><%= t('max_distance') %></th>
        <td><%= @mode.max_distance %> Km</td>
      </tr>
      <tr>
        <th><%= t('min_weight') %></th>
        <td><%= @mode.min_weight %> Kg</td>
      </tr>
      <tr>
        <th><%= t('max_weight') %></th>
        <td><%= @mode.max_weight %> Kg</td>
      </tr>
      <tr>
        <th><%= t('fixed_fee') %></th>
        <td><%= t('$') %> <%= @mode.fixed_fee %></td>
      </tr>
      <tr>
        <th><%= t('status') %></th>
        <td>
          <span class="<%= @mode.active ? 'ativo' : 'inativo' %>">
            <%= @mode.active ? t('active') : t('inactive') %>
          </span>
        </td>
      </tr>
    </table>
  </div>

  <div class="modes__btn-bottom">
    <%= button_to(t("edit"), edit_mode_path(@mode.id), method: :get, class: "btn btn-warning") %>
    <%= button_to(t("delete"), mode_path(@mode.id), method: :delete, class: "btn btn-danger") %>
  </div>

  <div class="modes__price-list">
    <h3><%= t('pricing_table') %></h3>
    <% if @prices.empty? %>
      <h5><%= t('this_modal_does_not_have_pricing_table') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('weight') %></th>
            <th scope="col"><%= t('price_per_km') %></th>
          </tr>
        </thead>
        <tbody>
          <% @prices.each do |price| %>
            <tr>
              <td><%= price.min_weight %> Kg</td>
              <td><%= price.max_weight %> Kg</td>
              <td>R$ <%= price.price_per_km %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="modes__deadline-list">
    <h3><%= t('deadlines_table') %></h3>
    <% if @deadlines.empty? %>
      <h5><%= t('this_modal_does_not_have_deadlines_table') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('distance') %></th>
            <th scope="col"><%= t('deadline') %></th>
          </tr>
        </thead>
        <tbody>
          <% @deadlines.each do |deadline| %>
            <tr>
              <td><%= deadline.min_distance %> Km</td>
              <td><%= deadline.max_distance %> Km</td>
              <td><%= deadline.deadline %> dias</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="modes__in_operation-list">
    <h3><%= t('in_operation_vehicles') %></h3>
    <% if @in_operation.empty? %>
      <h5><%= t('this_modal_does_not_have_in_operation_vehicles') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @in_operation.each do |vehicle| %>
            <tr>
              <td><%= vehicle.plate %></td>
              <td><%= vehicle.model %></td>
              <td><%= vehicle.category %></td>
              <td>
                <span class="
                  <%= if vehicle.status == 'in_operation'
                      'ativo'
                    elsif vehicle.status == 'in_transit'
                      'transito'
                    elsif vehicle.status == 'in_maintenance'
                      'inativo'
                    end
                  %>
                ">
                  <%= t(vehicle.status) %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="modes__in_maintenance-list">
    <h3><%= t('in_maintenance_vehicles') %></h3>
    <% if @in_maintenance.empty? %>
      <h5><%= t('this_modal_does_not_have_in_maintenance_vehicles') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @in_maintenance.each do |vehicle| %>
            <tr>
              <td><%= vehicle.plate %></td>
              <td><%= vehicle.model %></td>
              <td><%= vehicle.category %></td>
              <td>
                <span class="
                  <%= if vehicle.status == 'in_operation'
                      'ativo'
                    elsif vehicle.status == 'in_transit'
                      'transito'
                    elsif vehicle.status == 'in_maintenance'
                      'inativo'
                    end
                  %>
                ">
                  <%= t(vehicle.status) %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

</section>