config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get "/orders/:id/confirmed", to: "orders#show_confirmed", as: "order_confirmed"
  authenticate :user do
    resources :users, only: [:show, :edit, :update]
    resources :modes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'search_vehicles', on: :collection, as: 'search_vehicles'
    end
    resources :prices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'search_orders', on: :collection, as: 'search_all'
      resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :budgets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end

  resources :orders, only: [:show, :show_confirmed] do
    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :show]
    resources :order_products, only: [:index, :show]
    resources :order_addresses, only: [:index, :show]
    resources :budgets, only: [:index, :show]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    post 'returned', on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :orders, through: :order_addresses

  validates :person, :address_one, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :order
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  belongs_to :mode
  validates :min_distance, :max_distance, :deadline, :mode_id, presence: true
end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :vehicles
  has_many :prices
  has_many :deadlines
  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :addresses, through: :order_addresses
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  has_one :budgets, dependent: :destroy

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :order_products, allow_destroy: true

  enum status: { open:0, pending: 3, sent: 5, delivered: 10, canceled: 15, returned: 20 }

  enum condition: { on_time: 0, late: 10 }

  enum state: [ :AC, :AL, :AP, :AM, :BA, :CE, :DF, :ES, :GO, :MA, :MT, :MS, :MG, :PA, :PB, :PR, :PE, :PI, :RJ, :RN, :RS, :RO, :RR, :SC, :SP, :SE, :TO ]

  validates :distance, :status, presence: true
  validates_associated :order_products

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def addresses_attributes=(addresses_attributes)
    addresses_attributes.values.each do |address_attributes|
      self.addresses.build(address_attributes)
    end
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :order
  belongs_to :address

  # accepts_nested_attributes_for :address, allow_destroy: true
  validates_associated :address
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  accepts_nested_attributes_for :product, allow_destroy: true
  validates_associated :product, presence: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :mode
  validates :min_weight, :max_weight, :price_per_km, :mode_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products

  validates :code, :width, :height, :depth, :weight, presence: true

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :mode

  validates :mode_id, :plate, :brand, :model, :category, :year, :capacity, :status, presence: true

  enum status: { operational: 0, transit: 5, repair: 10 }
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :find_price, only: [:edit, :update, :destroy]

  def index
    @prices = Price.all
  end

  def destroy
    if @price.destroy
      flash[:notice] = "Preço excluído com sucesso"
      return redirect_to prices_path
    end
    flash.now[:alert] = "Erro ao excluir o preço"
    render :index, status: :unprocessable_entity
  end

  def new
    @price = Price.new
    @modes = Mode.all.order(:name)
  end

  def create
    @price = Price.new(price_params)
    if @price.save
      flash[:notice] = 'Preço cadastrado com sucesso'
      return redirect_to prices_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = 'Erro ao cadastrar preço'
    render :new, status: :unprocessable_entity
  end

  def edit
    @modes = Mode.all.order(:name)
  end

  def update
    if @price.update(price_params)
      flash[:notice] = "Preço atualizado com sucesso"
      return redirect_to prices_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = "Erro ao atualizar o preço"
    render :edit, status: :unprocessable_entity
  end

  private

  def price_params
    params.require(:price).permit(:min_weight, :max_weight, :price_per_km, :mode_id)
  end

  def find_price
    @price = Price.find(params[:id])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/prices/_form.html.erb
<% if price.errors.any? %>
  <div class="messages alert alert-warning" role="alert">
    <p><%= t('verify_the_following_errors') %>:</p>
    <ul>
      <% price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form">
  <%= form_with(model: price) do |f| %>
    <table class="prices__form table table-success table-striped">
      <tr>
        <th><%= f.label :min_weight, t('min_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :min_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_weight, t('max_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :max_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :price_per_km, t('price_per_km') << ' (R$)', class: "form-label" %></th>
        <td><%= f.number_field :price_per_km, step: '.01', class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :mode_id, t('mode'), class: "form-label" %></th>
        <td><%= f.collection_select :mode_id, @modes, :id, :name, { include_blank: true }, { class: "form-select" } %></td>
      </tr>
    </table>
    <div class="prices__btn">
      <%= f.submit t('save'), class: "btn btn-success" %>
    </div>  
  <% end %>
</div>

app/views/prices/edit.html.erb
<section>
  <div class="prices">
    <h1><%= t('edit') << " " << t('price') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), prices_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    <%= render partial: "form", locals: { price: @price } %>
  </div>
</section>

app/views/prices/index.html.erb
<section>
  <div class="prices">
    <h1><%= t('prices') %></h1>
    <div class="page__top">
      <%= link_to t('new_price'), new_price_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="prices__list">
    <% if @prices.empty? %>
      <h3><%= t('no_prices_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('weight') %></th>
            <th scope="col"><%= t('price_per_km') %></th>
            <th scope="col"><%= t('mode') %></th>
            <th scope="col" colspan="2"><%= t('actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @prices.each do |price| %>
            <tr>
              <td class="table__td-width"><%= price.min_weight %> Kg</td>
              <td class="table__td-width"><%= price.max_weight %> Kg</td>
              <td class="table__td-width">R$ <%= price.price_per_km %></td>
              <td class="table__td-width"><%= price.mode.name %></td>
              <td><%= button_to(t("edit"), edit_price_path(price.id), class: "btn btn-warning prices__btn", method: :get) %></td>
              <td><%= button_to(t("delete"),
                price_path(price.id),
                form: { data: { turbo_confirm: "Tem certeza?" }},
                class: "btn btn-danger prices__btn",
                method: :delete) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/prices/new.html.erb
<section>
  <div class="prices">
    <h1><%= t('new_price') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), prices_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    <%= render partial: "form", locals: { price: @price } %>
  </div>
</section>