config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get "/orders/:id/confirmed", to: "orders#show_confirmed", as: "order_confirmed"
  authenticate :user do
    resources :users, only: [:show, :edit, :update]
    resources :modes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'search_vehicles', on: :collection, as: 'search_vehicles'
    end
    resources :prices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'search_orders', on: :collection, as: 'search_all'
      resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :order_addresses, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :budgets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end

  resources :orders, only: [:show, :show_confirmed] do
    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :show]
    resources :order_products, only: [:index, :show]
    resources :order_addresses, only: [:index, :show]
    resources :budgets, only: [:index, :show]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    post 'returned', on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :orders, through: :order_addresses

  validates :person, :address_one, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :order
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  belongs_to :mode
  validates :min_distance, :max_distance, :deadline, :mode_id, presence: true
end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :vehicles
  has_many :prices
  has_many :deadlines
  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_addresses, dependent: :destroy
  has_many :addresses, through: :order_addresses
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  has_one :budgets, dependent: :destroy

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :order_products, allow_destroy: true

  enum status: { open:0, pending: 3, sent: 5, delivered: 10, canceled: 15, returned: 20 }

  enum condition: { on_time: 0, late: 10 }

  enum state: [ :AC, :AL, :AP, :AM, :BA, :CE, :DF, :ES, :GO, :MA, :MT, :MS, :MG, :PA, :PB, :PR, :PE, :PI, :RJ, :RN, :RS, :RO, :RR, :SC, :SP, :SE, :TO ]

  validates :distance, :status, presence: true
  validates_associated :order_products

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def addresses_attributes=(addresses_attributes)
    addresses_attributes.values.each do |address_attributes|
      self.addresses.build(address_attributes)
    end
  end
end

app/models/order_address.rb
class OrderAddress < ApplicationRecord
  belongs_to :order
  belongs_to :address

  # accepts_nested_attributes_for :address, allow_destroy: true
  validates_associated :address
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  accepts_nested_attributes_for :product, allow_destroy: true
  validates_associated :product, presence: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :mode
  validates :min_weight, :max_weight, :price_per_km, :mode_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products

  validates :code, :width, :height, :depth, :weight, presence: true

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :mode

  validates :mode_id, :plate, :brand, :model, :category, :year, :capacity, :status, presence: true

  enum status: { operational: 0, transit: 5, repair: 10 }
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :find_vehicle, only: [:show, :edit, :update, :destroy]

  def index
    @vehicles = Vehicle.all
  end

  def show
  end

  def destroy
    if @vehicle.destroy
      flash[:notice] = "Veículo apagado com sucesso"
      return redirect_to vehicles_path
    end
    flash.now[:alert] = "Erro ao apagar o veículo"
    render :show, status: :unprocessable_entity
  end

  def new
    @vehicle = Vehicle.new
    @modes = Mode.all.order(:name)
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      flash[:notice] = "Veículo criado com sucesso"
      return redirect_to vehicles_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = "Erro ao criar o veículo"
    render :new, status: :unprocessable_entity
  end

  def edit
    @modes = Mode.all.order(:name)
  end

  def update
    if @vehicle.update(vehicle_params)
      flash[:notice] = "Veículo atualizado com sucesso"
      return redirect_to @vehicle
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = "Erro ao atualizar o veículo"
    render :edit, status: :unprocessable_entity
  end

  def search_vehicles
    @vehicles = Vehicle.where('plate LIKE ? OR brand LIKE ? OR model LIKE ? OR category LIKE ? OR status LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%")
    if @vehicles.empty?
      flash[:alert] = 'Nenhum veículo encontrado'
    end
    render :index
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:mode_id, :plate, :brand, :model, :category, :year, :capacity, :status)
  end

  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<% if vehicle.errors.any? %>
  <div class="messages alert alert-warning" role="alert">
    <p><%= t('verify_the_following_errors') %>:</p>
    <ul>
      <% vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form">
  <%= form_with(model: vehicle) do |f| %>
    <table class="vehicles__form table table-success table-striped">
      <tr>
        <th class=""><%= f.label :mode_id, t('mode'), class: "form-label" %></th>
        <td><%= f.collection_select :mode_id, @modes, :id, :name, { include_blank: true }, { class: "form-select" } %></td>
      </tr>
      <tr>
        <th><%= f.label :plate, t('plate'), class: "form-label" %></th>
        <td><%= f.text_field :plate, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :brand, t('brand'), class: "form-label" %></th>
        <td><%= f.text_field :brand, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :model, t('model'), class: "form-label" %></th>
        <td><%= f.text_field :model, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :category, t('category'), class: "form-label" %></th>
        <td><%= f.text_field :category, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :year, t('year'), class: "form-label" %></th>
        <td><%= f.number_field :year, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :capacity, t('capacity'), class: "form-label" %></th>
        <td><%= f.number_field :capacity, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :status, t('status'), class: "form-label" %></th>
        <td>
          <%= f.select :status, Vehicle.statuses.keys, { include_blank: true }, { class: "form-select" } %>
        </td>
      </tr>
    </table>
    <div class="vehicles__btn">
      <%= f.submit t('save'), class: "btn btn-success" %>
    </div>  
  <% end %>
</div>

app/views/vehicles/edit.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('edit') << " " << t('vehicle') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), vehicles_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    <%= render partial: "form", locals: { vehicle: @vehicle } %>
  </div>
</section>

app/views/vehicles/index.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('vehicles') %></h1>
    <div class="page__top">
      <div><%= link_to t('new_vehicle'), new_vehicle_path, class: "btn btn-primary" %></div>
      <div class="page__top-search">
        <%= form_with(url: search_vehicles_vehicles_path, method: :get) do |f| %>
          <%= f.text_field :query, class: "form-control", placeholder: "Buscar..." %>
          <%= f.submit t('search'), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="modes__list">
    <% if @vehicles.empty? %>
      <h3><%= t('no_vehicles_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
            <th scope="col"><%= t('load') %></th>
            <th scope="col"><%= t('mode') %></th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @vehicles.each do |vehicle| %>
            <tr>
              <td scope="row" class="table__td-width"><%= link_to vehicle.plate, vehicle_path(vehicle.id) %></td>
              <td class="table__td-width"><%= vehicle.model %></td>
              <td class="table__td-width"><%= vehicle.category %></td>
              <td class="table__td-width"><%= vehicle.capacity %></td>
              <td class="table__td-width"><%= vehicle.mode.name %></td>
              <td>
                <span class="
                  <%= if vehicle.status == 'operational'
                     'ativo'
                    elsif vehicle.status == 'transit'
                     'transito'
                    elsif vehicle.status == 'repair'
                     'inativo'
                    end
                  %>
                ">
                  <%= if vehicle.status == 'operational'
                     t('operational')
                    elsif vehicle.status == 'transit'
                      t('transit')
                    elsif vehicle.status == 'repair'
                     t('repair')
                    end
                  %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/vehicles/new.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('new_vehicle') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), vehicles_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    <%= render partial: "form", locals: { vehicle: @vehicle } %>
  </div>
</section>

app/views/vehicles/show.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('vehicle') %></h1>
    <div class="page__top">
      <%= button_to(t("back"), vehicles_path, method: :get, class: "btn btn-primary back__btn") %>
    </div>
    
    <table class="vehicles__table table table-success table-striped">
      <tr>
        <th><%= t('plate') %></th>
        <td><%= @vehicle.plate %></td>
      </tr>
      <tr>
        <th><%= t('brand') %></th>
        <td><%= @vehicle.brand %></td>
      </tr>
      <tr>
        <th><%= t('model') %></th>
        <td><%= @vehicle.model %></td>
      </tr>
      <tr>
        <th><%= t('category') %></th>
        <td><%= @vehicle.category %></td>
      </tr>
      <tr>
        <th><%= t('year') %></th>
        <td><%= @vehicle.year %></td>
      </tr>
      <tr>
        <th><%= t('capacity') %></th>
        <td><%= @vehicle.capacity %> Kg</td>
      </tr>
      <tr>
        <th><%= t('status') %></th>
        <td>
          <span class="
            <%= if @vehicle.status == 'operational'
                'ativo'
              elsif @vehicle.status == 'transit'
                'transito'
              elsif @vehicle.status == 'repair'
                'inativo'
              end
            %>
          ">
            <%= if @vehicle.status == 'operational'
                t('operational')
              elsif @vehicle.status == 'transit'
                t('transit')
              elsif @vehicle.status == 'repair'
                t('repair')
              end
            %>
          </span>
        </td>
      </tr>
    </table>
  </div>
  <div class="vehicles__btn-bottom">
    <%= button_to(t("edit"), edit_vehicle_path(@vehicle.id), method: :get, class: "btn btn-warning") %>
    <%= button_to(t("delete"), vehicle_path(@vehicle.id), method: :delete, class: "btn btn-danger") %>
  </div>
</section>